services:
  ips:
    build:
      context: ./IPS
      dockerfile: Dockerfile
    container_name: ips
    ports:
      - "8000:8080"
    networks:
      - cyber

  victim:
    build:
      context: ./victim
      dockerfile: Dockerfile  
    container_name: victim
    expose:
      - "8080"
    networks:
      - cyber 
  attacker1:
    build:
      context: ./attackers/attacker
    environment:
      - target_host=http://ips:8080
      - target_routes=/
      - concurrency=1
    networks:
      - cyber 
    depends_on:
      - victim
    deploy:
      replicas: 2
  exploration-attacker:
    build:
      context: ./attackers/exploration
    environment:
      - target_host=http://ips:8080
      - concurrency=1
    networks:
      - cyber 
    depends_on:
      - victim
    deploy:
      replicas: 2
  slower-attacker:
    build:
      context: ./attackers/slowerFaster
    environment:
      - target_host=http://ips:8080
      - concurrency=1
    networks:
      - cyber 
    depends_on:
      - victim
    deploy:
      replicas: 2
  error-attacker:
    build:
      context: ./attackers/error
    environment:
      - target_host=http://ips:8080
      - concurrency=1
    networks:
      - cyber 
    depends_on:
      - victim
    deploy:
      replicas: 2


networks:
  cyber:
    driver: bridge
